FROM registry.access.redhat.com/ubi9/ubi

LABEL description="R-Shiny image based on RHEL UBI9"
ENV LANG en_US.UTF-8
USER root

RUN dnf update -y && \
    dnf install -y epel-release https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    /usr/bin/crb enable && \
    dnf update -y && \
    dnf install -y flexiblas-* \
        https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/openblas-openmp64-0.3.21-2.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/flexiblas-openblas-openmp64-3.0.4-8.el9.x86_64.rpm \
        https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/pkgconf-pkg-config-1.7.3-10.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/flexiblas-3.0.4-8.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/libtirpc-1.3.3-2.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/perl-libs-5.32.1-480.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/perl-Unicode-EastAsianWidth-12.0-7.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/texinfo-6.7-15.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/texinfo-tex-6.7-15.el9.x86_64.rpm \
        https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/flexiblas-netlib64-3.0.4-8.el9.x86_64.rpm \
        https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/flexiblas-devel-3.0.4-8.el9.x86_64.rpm \
        https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/libtirpc-devel-1.3.3-2.el9.x86_64.rpm \
        R libsodium-devel.x86_64 libgit2-devel.x86_64 libcurl-devel cmake glibc-langpack-en && \
    R --version && \
    R -q -e 'install.packages(c("dplyr", "rpart","utf8", "generics", "bslib", "tibble", "xgboost", "httr", "jsonlite"), repos = "https://cran.rstudio.com/")'

RUN mkdir /application
WORKDIR /application

USER 1001
ENTRYPOINT R -s -e 'library("shiny"); runApp(host = "0.0.0.0", port = 3838)'
