kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-breastcancer-bucket
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: breastcancer-bucket
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: none
  AWS_S3_BUCKET: breast-cancer
  AWS_S3_ENDPOINT: http://minio-service.minio.svc.cluster.local:9000
  AWS_SECRET_ACCESS_KEY: minio123
type: Opaque
